### ISSUE TITLE
Roadmap 201609

### ISSUE THREAD

**Issue by larshp** [abaplint/abaplint#86]
### Basics
- [x] EXIT or CHECK https://github.com/larshp/abaplint/issues/85
- [x] automatic gh-pages deploy https://github.com/larshp/abaplint/issues/17
- [x] get version when run in browser/web https://github.com/larshp/abaplint/issues/82
- [x] performance https://github.com/larshp/abaplint/issues/60
### Automatic downgrade ABAP code
- [x] Extend AST, currently only single statements
- [ ] AST walkers?
- [ ] Typing? # #92 
- [ ] Better web AST explorer
- [ ] AST manipulation
- [ ] Generate code from AST
- [ ] Downgrade logic #91 

as separate executable?
### For the future
- adding more checks
- automatic fixing of issues
- automatic upgrade code
- typeahead functionallity
- basic syntax checks
- data flow analysis and visualization

**Comment by larshp** [comment]
outdated, closing
